In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import scipy.io
features = scipy.io.loadmat('RESNETRico.mat')

In [3]:
features.items()

dict_items([('__header__', b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Jan 22 23:30:49 2020'), ('__version__', '1.0'), ('__globals__', []), ('interresnetrico', array([[-0.88956803, -0.74412704, -1.1995041 , ..., -1.6957443 ,
        -0.23405352,  0.5585592 ],
       [-0.82831275, -1.0457783 , -2.0878148 , ..., -1.0759813 ,
         0.01785786,  0.10638709],
       [-1.7050315 ,  0.12494949, -1.6913018 , ..., -0.70905036,
        -0.2887151 ,  1.0568686 ],
       ...,
       [-3.5950396 , -2.123115  , -1.8741007 , ..., -0.46376246,
        -2.5234246 ,  0.83890796],
       [-0.8809616 ,  1.0915143 ,  0.80549836, ..., -2.3544033 ,
        -0.16969495,  1.0819693 ],
       [-1.6409075 , -0.7211896 , -0.46662235, ..., -2.6514275 ,
        -0.3253887 ,  2.062448  ]], dtype=float32))])

In [5]:
data=features["interresnetrico"]

In [6]:
data

array([[-0.88956803, -0.74412704, -1.1995041 , ..., -1.6957443 ,
        -0.23405352,  0.5585592 ],
       [-0.82831275, -1.0457783 , -2.0878148 , ..., -1.0759813 ,
         0.01785786,  0.10638709],
       [-1.7050315 ,  0.12494949, -1.6913018 , ..., -0.70905036,
        -0.2887151 ,  1.0568686 ],
       ...,
       [-3.5950396 , -2.123115  , -1.8741007 , ..., -0.46376246,
        -2.5234246 ,  0.83890796],
       [-0.8809616 ,  1.0915143 ,  0.80549836, ..., -2.3544033 ,
        -0.16969495,  1.0819693 ],
       [-1.6409075 , -0.7211896 , -0.46662235, ..., -2.6514275 ,
        -0.3253887 ,  2.062448  ]], dtype=float32)

In [7]:
dataf = pd.DataFrame()

In [8]:
dataf_new = pd.concat([dataf, pd.DataFrame(data)], axis=1)

In [9]:
dataf_new

0         1         2         3         4         5         6    \
0    -0.889568 -0.744127 -1.199504 -2.748461 -0.839458  1.345607 -2.919126   
1    -0.828313 -1.045778 -2.087815 -3.353579 -1.690721  2.055481 -2.143452   
2    -1.705032  0.124949 -1.691302 -3.367152 -1.421503  1.458051 -1.115408   
3    -2.129903 -0.167782  0.473605  1.104942  2.083377  1.412527 -0.911291   
4    -0.529483  0.062291 -1.268661 -2.263318 -1.216207  0.370471 -2.059504   
...        ...       ...       ...       ...       ...       ...       ...   
9672 -1.538506  1.753641 -1.026061 -1.055811 -0.662133  1.669089 -3.171782   
9673 -0.514712 -0.632938 -1.371444 -2.785903 -0.837988  2.027846 -1.361226   
9674 -3.595040 -2.123115 -1.874101 -2.133861 -2.250522 -1.020245 -3.249574   
9675 -0.880962  1.091514  0.805498  0.099322  1.876431  4.269727  0.821350   
9676 -1.640908 -0.721190 -0.466622 -1.067630 -1.208264  1.585464 -1.029593   

           7         8         9    ...       990       991       992  \
0    -1.392561 -0.595446 -1.215719  ... -1.411068 -1.088410 -1.270798   
1    -2.605685 -3.004198 -2.233716  ... -1.704411 -1.390666 -0.268684   
2    -1.253017 -1.301832 -1.277127  ...  0.040224 -0.554237 -1.341914   
3    -2.545690 -2.152527 -1.236064  ... -1.662661 -2.098126 -1.983992   
4    -1.658103 -1.212902 -0.342392  ...  0.249023 -1.655772 -1.764482   
...        ...       ...       ...  ...       ...       ...       ...   
9672 -2.567410 -2.391514 -1.025848  ... -1.443935 -1.972948 -2.659031   
9673 -1.972303 -2.270256 -1.692514  ... -1.109995 -1.478742 -1.570283   
9674 -2.176316 -3.561570 -2.067213  ... -2.934060 -3.379283 -0.733731   
9675 -2.134999 -1.901049 -1.128096  ... -1.918796 -1.024687 -2.992501   
9676 -1.045579 -2.110245 -2.900670  ... -1.488841 -3.036849 -3.582553   

           993       994       995       996       997       998       999  
0    -1.042473 -1.357330 -1.634711 -0.978048 -1.695744 -0.234054  0.558559  
1    -0.567206 -1.750308 -1.227306 -0.099696 -1.075981  0.017858  0.106387  
2     0.256509 -0.904656 -0.473428 -0.389022 -0.709050 -0.288715  1.056869  
3    -2.261464 -2.587873  0.053293 -2.288320 -2.027185 -0.198659  2.155125  
4    -0.971342 -1.692358 -1.803632 -0.937436 -1.923607 -0.306954  0.141978  
...        ...       ...       ...       ...       ...       ...       ...  
9672 -2.333443 -1.865250 -2.375766 -1.254241 -2.380501 -0.736898  0.743945  
9673 -1.380183 -2.345481 -1.861876 -0.715537 -1.841057 -0.196930 -0.788610  
9674 -4.363718 -4.574227 -3.208127 -3.301821 -0.463762 -2.523425  0.838908  
9675 -2.253113 -2.718245 -1.055718 -2.013867 -2.354403 -0.169695  1.081969  
9676 -2.378007 -3.821906 -2.092377 -1.268794 -2.651428 -0.325389  2.062448  

[9677 rows x 1000 columns]

In [65]:
from sklearn import preprocessing
dataf_normalized = preprocessing.normalize(dataf_new)

In [66]:
dataf_normalized

array([[-0.01973848, -0.01651132, -0.0266156 , ..., -0.0376266 ,
        -0.00519338,  0.01239378],
       [-0.01430051, -0.01805497, -0.03604534, ..., -0.01857641,
         0.00030831,  0.00183673],
       [-0.02976089,  0.00218096, -0.02952124, ..., -0.01237629,
        -0.00503945,  0.01844737],
       ...,
       [-0.04057031, -0.02395953, -0.02114938, ..., -0.0052336 ,
        -0.02847705,  0.00946714],
       [-0.01611815,  0.01997045,  0.01473747, ..., -0.04307638,
        -0.00310475,  0.01979581],
       [-0.02586745, -0.01136892, -0.00735589, ..., -0.0417974 ,
        -0.00512946,  0.03251266]], dtype=float32)

In [67]:
dataf_normalizedframe = pd.concat([df, pd.DataFrame(dataf_normalized)], axis=1)

In [68]:
dataf_normalizedframe

0         1         2         3         4         5         6    \
0    -0.019738 -0.016511 -0.026616 -0.060985 -0.018627  0.029857 -0.064772   
1    -0.014301 -0.018055 -0.036045 -0.057898 -0.029190  0.035487 -0.037006   
2    -0.029761  0.002181 -0.029521 -0.058773 -0.024812  0.025450 -0.019469   
3    -0.034013 -0.002679  0.007563  0.017645  0.033270  0.022557 -0.014552   
4    -0.011054  0.001300 -0.026485 -0.047250 -0.025390  0.007734 -0.042995   
...        ...       ...       ...       ...       ...       ...       ...   
9672 -0.023886  0.027226 -0.015930 -0.016392 -0.010280  0.025914 -0.049244   
9673 -0.009990 -0.012285 -0.026619 -0.054073 -0.016265  0.039360 -0.026421   
9674 -0.040570 -0.023960 -0.021149 -0.024081 -0.025397 -0.011514 -0.036672   
9675 -0.016118  0.019970  0.014737  0.001817  0.034331  0.078119  0.015027   
9676 -0.025867 -0.011369 -0.007356 -0.016830 -0.019047  0.024993 -0.016231   

           7         8         9    ...       990       991       992  \
0    -0.030899 -0.013212 -0.026975  ... -0.031310 -0.024151 -0.028198   
1    -0.044986 -0.051866 -0.038564  ... -0.029426 -0.024009 -0.004639   
2    -0.021871 -0.022723 -0.022292  ...  0.000702 -0.009674 -0.023423   
3    -0.040652 -0.034374 -0.019739  ... -0.026551 -0.033505 -0.031682   
4    -0.034616 -0.025321 -0.007148  ...  0.005199 -0.034567 -0.036836   
...        ...       ...       ...  ...       ...       ...       ...   
9672 -0.039861 -0.037130 -0.015927  ... -0.022418 -0.030631 -0.041283   
9673 -0.038282 -0.044065 -0.032851  ... -0.021545 -0.028702 -0.030479   
9674 -0.024560 -0.040193 -0.023329  ... -0.033111 -0.038135 -0.008280   
9675 -0.039062 -0.034782 -0.020640  ... -0.035106 -0.018748 -0.054751   
9676 -0.016483 -0.033266 -0.045726  ... -0.023470 -0.047873 -0.056476   

           993       994       995       996       997       998       999  
0    -0.023131 -0.030118 -0.036272 -0.021702 -0.037627 -0.005193  0.012394  
1    -0.009793 -0.030218 -0.021189 -0.001721 -0.018576  0.000308  0.001837  
2     0.004477 -0.015791 -0.008264 -0.006790 -0.012376 -0.005039  0.018447  
3    -0.036113 -0.041326  0.000851 -0.036542 -0.032372 -0.003172  0.034415  
4    -0.020278 -0.035331 -0.037654 -0.019570 -0.040158 -0.006408  0.002964  
...        ...       ...       ...       ...       ...       ...       ...  
9672 -0.036228 -0.028959 -0.036885 -0.019473 -0.036959 -0.011441  0.011550  
9673 -0.026789 -0.045525 -0.036138 -0.013888 -0.035734 -0.003822 -0.015307  
9674 -0.049245 -0.051621 -0.036204 -0.037261 -0.005234 -0.028477  0.009467  
9675 -0.041223 -0.049733 -0.019316 -0.036846 -0.043076 -0.003105  0.019796  
9676 -0.037487 -0.060249 -0.032984 -0.020001 -0.041797 -0.005129  0.032513  

[9677 rows x 1000 columns]

In [52]:
labels=scipy.io.loadmat('labels.mat')

In [53]:
labels.items()

dict_items([('__header__', b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun May 29 09:57:48 2022'), ('__version__', '1.0'), ('__globals__', []), ('classenew', array([[array(['Bad'], dtype='<U3')],
       [array(['Good'], dtype='<U4')],
       [array(['Bad'], dtype='<U3')],
       ...,
       [array(['Good'], dtype='<U4')],
       [array(['Good'], dtype='<U4')],
       [array(['Bad'], dtype='<U3')]], dtype=object)), ('labels', array([[1],
       [2],
       [1],
       ...,
       [2],
       [2],
       [1]], dtype=uint8))])

In [54]:
Classes=labels["labels"]

In [55]:
Classes

array([[1],
       [2],
       [1],
       ...,
       [2],
       [2],
       [1]], dtype=uint8)

In [56]:
df = pd.DataFrame()

In [57]:
df_new = pd.concat([df, pd.DataFrame(Classes)], axis=1)

In [58]:
df_new

0
0     1
1     2
2     1
3     2
4     2
...  ..
9672  2
9673  2
9674  2
9675  2
9676  1

[9677 rows x 1 columns]

In [69]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import RandomizedSearchCV

from sklearn import tree
clf = AdaBoostClassifier(learning_rate= 0.01, n_estimators=100)
A=np.mean(cross_val_score(clf,dataf_normalizedframe,df_new,cv=5,scoring="accuracy"))
r=np.mean(cross_val_score(clf,dataf_normalizedframe,df_new,cv=5,scoring="recall_weighted"))
p=np.mean(cross_val_score(clf,dataf_normalizedframe,df_new,cv=5,scoring="precision_weighted"))
print('A=',A*100)
print('r=',r*100)
print('p=',p*100)

C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  ret

A= 70.3523768338779
r= 70.3523768338779
p= 50.7192016475957


C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [72]:
from sklearn.model_selection import cross_val_score
from sklearn import svm, datasets
import numpy as np
# Model auc score using all the features
#clf = svm.SVC(kernel='sigmoid')
# clf = svm.SVC(kernel='poly', degree=8)
model = svm.SVC(kernel='rbf', C=1)
#model = svm.SVC(kernel = 'linear', random_state = 0)
A=np.mean(cross_val_score(model,dataf_normalizedframe,df_new,cv=5,scoring="accuracy"))
r=np.mean(cross_val_score(model,dataf_normalizedframe,df_new,cv=5,scoring="recall_weighted"))
p=np.mean(cross_val_score(model,dataf_normalizedframe,df_new,cv=5,scoring="precision_weighted"))
print('A=',A*100)
print('r=',r*100)
print('p=',p*100)

C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  ret

A= 70.37305400730348
r= 70.37305400730348
p= 49.53605529813826


C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
