In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import scipy.io
features = scipy.io.loadmat('DenseNetricofeat.mat')

In [3]:
features.items()

dict_items([('__header__', b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Jun  2 10:30:41 2022'), ('__version__', '1.0'), ('__globals__', []), ('interdicenetrico', array([[-0.11433402, -0.23565495, -1.3580118 , ..., -3.3512032 ,
        -1.566569  ,  0.39074987],
       [-2.3915563 , -0.7709366 , -1.1637598 , ..., -1.432366  ,
        -0.6658016 ,  0.47946241],
       [-2.331447  , -1.1662167 , -2.0273528 , ..., -1.6943618 ,
        -0.25753906,  0.33022064],
       ...,
       [-0.5543062 , -0.07677884,  0.5166185 , ..., -2.4726655 ,
        -0.2970361 ,  1.1995248 ],
       [-0.9063151 , -1.5889524 ,  1.4474401 , ..., -1.9854273 ,
        -1.0328443 ,  0.9848792 ],
       [-1.6224673 , -1.0930433 , -2.4533777 , ..., -2.1019142 ,
        -0.63184917,  2.0585244 ]], dtype=float32))])

In [4]:
data=features["interdicenetrico"]

In [5]:
data

array([[-0.11433402, -0.23565495, -1.3580118 , ..., -3.3512032 ,
        -1.566569  ,  0.39074987],
       [-2.3915563 , -0.7709366 , -1.1637598 , ..., -1.432366  ,
        -0.6658016 ,  0.47946241],
       [-2.331447  , -1.1662167 , -2.0273528 , ..., -1.6943618 ,
        -0.25753906,  0.33022064],
       ...,
       [-0.5543062 , -0.07677884,  0.5166185 , ..., -2.4726655 ,
        -0.2970361 ,  1.1995248 ],
       [-0.9063151 , -1.5889524 ,  1.4474401 , ..., -1.9854273 ,
        -1.0328443 ,  0.9848792 ],
       [-1.6224673 , -1.0930433 , -2.4533777 , ..., -2.1019142 ,
        -0.63184917,  2.0585244 ]], dtype=float32)

In [6]:
df = pd.DataFrame()

In [7]:
dataf_new = pd.concat([df, pd.DataFrame(data)], axis=1)

In [8]:
dataf_new

0         1         2         3         4         5         6    \
0    -0.114334 -0.235655 -1.358012 -1.194040 -0.219160  1.098917 -3.595458   
1    -2.391556 -0.770937 -1.163760 -1.344385 -0.911975  3.095090 -1.919486   
2    -2.331447 -1.166217 -2.027353 -2.211011 -0.916902  2.234265 -0.812476   
3    -1.733341 -1.706196  0.592438  1.973178  2.629775  1.227385 -1.534082   
4    -1.433207 -1.194132 -0.962656 -0.275577 -0.251970  1.884913 -1.775828   
...        ...       ...       ...       ...       ...       ...       ...   
9672 -1.122425  0.234790  0.220200  0.541921  1.141393  2.472187 -0.412149   
9673 -1.207234 -0.973850 -0.337597 -1.087175 -0.059191  1.864319 -1.461753   
9674 -0.554306 -0.076779  0.516618  0.265747 -0.178674  0.072731 -3.798334   
9675 -0.906315 -1.588952  1.447440  1.011178  1.107589  3.435620 -0.437020   
9676 -1.622467 -1.093043 -2.453378 -0.525240 -1.125610  0.878518 -2.337538   

           7         8         9    ...       990       991       992  \
0    -0.705815 -1.171473 -2.047027  ... -0.119466 -2.412701 -2.536574   
1    -0.608944 -1.050886 -0.190992  ...  1.197846 -0.839287 -1.170768   
2    -0.118496 -0.130909  0.229219  ...  0.225675 -0.364555 -0.096231   
3    -2.709578 -3.079697  0.977479  ... -2.596537 -2.803654 -2.965143   
4    -0.140145 -1.052627  0.111563  ...  0.266838 -1.110205 -1.188275   
...        ...       ...       ...  ...       ...       ...       ...   
9672 -0.835195 -1.774687 -0.051467  ... -1.478428 -1.960459 -1.745695   
9673  0.092769 -1.238269 -0.212653  ... -0.333995 -1.717352 -1.089830   
9674 -1.499908 -2.277317 -1.167580  ... -0.530453 -2.512695 -2.077087   
9675 -1.195347 -2.450726  0.099715  ...  0.312457 -2.262446 -0.266865   
9676 -1.691456 -2.440484 -1.217885  ... -0.727132 -2.176998 -1.625771   

           993       994       995       996       997       998       999  
0     0.210639 -0.579721 -1.604903 -0.643543 -3.351203 -1.566569  0.390750  
1     0.085952 -0.642038  0.081008 -0.748450 -1.432366 -0.665802  0.479462  
2     0.253760  0.707172 -1.200303 -1.714300 -1.694362 -0.257539  0.330221  
3    -2.745771 -3.752298 -1.894969 -3.136979 -5.060113 -2.040644 -1.115720  
4    -0.280507 -0.962662 -0.808447 -0.915107 -1.056693 -1.570751  0.861396  
...        ...       ...       ...       ...       ...       ...       ...  
9672 -1.693008 -1.608685 -1.938204 -1.095740 -2.041443 -1.019644  0.420883  
9673 -0.837292 -0.853296 -1.285401 -1.382535 -1.639333 -0.966629  0.642349  
9674 -0.965568 -1.045425 -2.184214 -2.565173 -2.472666 -0.297036  1.199525  
9675  0.523996 -1.328320 -1.515062 -1.944265 -1.985427 -1.032844  0.984879  
9676  0.755993 -0.017313  0.783612 -0.766351 -2.101914 -0.631849  2.058524  

[9677 rows x 1000 columns]

In [9]:
from sklearn import preprocessing
dataf_normalized = preprocessing.normalize(dataf_new)

In [10]:
dataf_normalized

array([[-0.00200046, -0.00412317, -0.02376065, ..., -0.05863481,
        -0.0274097 ,  0.00683681],
       [-0.04794962, -0.01545693, -0.02333286, ..., -0.02871829,
        -0.01334902,  0.009613  ],
       [-0.04181038, -0.02091404, -0.03635699, ..., -0.03038539,
        -0.00461851,  0.00592192],
       ...,
       [-0.00753192, -0.00104327,  0.00701982, ..., -0.03359859,
        -0.00403613,  0.01629915],
       [-0.01586612, -0.0278165 ,  0.02533916, ..., -0.03475726,
        -0.01808116,  0.01724148],
       [-0.02469103, -0.01663415, -0.03733598, ..., -0.03198734,
        -0.0096156 ,  0.03132703]], dtype=float32)

In [11]:
dataf_normalizedframe = pd.concat([df, pd.DataFrame(dataf_normalized)], axis=1)

In [12]:
dataf_normalizedframe

0         1         2         3         4         5         6    \
0    -0.002000 -0.004123 -0.023761 -0.020892 -0.003835  0.019227 -0.062908   
1    -0.047950 -0.015457 -0.023333 -0.026954 -0.018285  0.062055 -0.038485   
2    -0.041810 -0.020914 -0.036357 -0.039651 -0.016443  0.040068 -0.014570   
3    -0.019948 -0.019636  0.006818  0.022708  0.030265  0.014125 -0.017655   
4    -0.032568 -0.027135 -0.021875 -0.006262 -0.005726  0.042832 -0.040354   
...        ...       ...       ...       ...       ...       ...       ...   
9672 -0.023530  0.004922  0.004616  0.011361  0.023928  0.051827 -0.008640   
9673 -0.026264 -0.021187 -0.007345 -0.023652 -0.001288  0.040559 -0.031801   
9674 -0.007532 -0.001043  0.007020  0.003611 -0.002428  0.000988 -0.051612   
9675 -0.015866 -0.027816  0.025339  0.017702  0.019390  0.060145 -0.007651   
9676 -0.024691 -0.016634 -0.037336 -0.007993 -0.017130  0.013369 -0.035573   

           7         8         9    ...       990       991       992  \
0    -0.012349 -0.020497 -0.035816  ... -0.002090 -0.042214 -0.044382   
1    -0.012209 -0.021070 -0.003829  ...  0.024016 -0.016827 -0.023473   
2    -0.002125 -0.002348  0.004111  ...  0.004047 -0.006538 -0.001726   
3    -0.031183 -0.035443  0.011249  ... -0.029882 -0.032266 -0.034124   
4    -0.003185 -0.023920  0.002535  ...  0.006064 -0.025228 -0.027002   
...        ...       ...       ...  ...       ...       ...       ...   
9672 -0.017509 -0.037204 -0.001079  ... -0.030994 -0.041099 -0.036597   
9673  0.002018 -0.026939 -0.004626  ... -0.007266 -0.037362 -0.023710   
9674 -0.020381 -0.030944 -0.015865  ... -0.007208 -0.034143 -0.028223   
9675 -0.020926 -0.042903  0.001746  ...  0.005470 -0.039607 -0.004672   
9676 -0.025741 -0.037140 -0.018534  ... -0.011066 -0.033130 -0.024741   

           993       994       995       996       997       998       999  
0     0.003685 -0.010143 -0.028080 -0.011260 -0.058635 -0.027410  0.006837  
1     0.001723 -0.012873  0.001624 -0.015006 -0.028718 -0.013349  0.009613  
2     0.004551  0.012682 -0.021525 -0.030743 -0.030385 -0.004619  0.005922  
3    -0.031600 -0.043183 -0.021808 -0.036102 -0.058234 -0.023485 -0.012840  
4    -0.006374 -0.021875 -0.018371 -0.020795 -0.024012 -0.035693  0.019574  
...        ...       ...       ...       ...       ...       ...       ...  
9672 -0.035492 -0.033724 -0.040632 -0.022971 -0.042797 -0.021376  0.008823  
9673 -0.018216 -0.018564 -0.027965 -0.030078 -0.035665 -0.021030  0.013975  
9674 -0.013120 -0.014205 -0.029679 -0.034856 -0.033599 -0.004036  0.016299  
9675  0.009173 -0.023254 -0.026523 -0.034037 -0.034757 -0.018081  0.017241  
9676  0.011505 -0.000263  0.011925 -0.011662 -0.031987 -0.009616  0.031327  

[9677 rows x 1000 columns]

In [13]:
labels=scipy.io.loadmat('labels.mat')

In [14]:
labels.items()

dict_items([('__header__', b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun May 29 09:57:48 2022'), ('__version__', '1.0'), ('__globals__', []), ('classenew', array([[array(['Bad'], dtype='<U3')],
       [array(['Good'], dtype='<U4')],
       [array(['Bad'], dtype='<U3')],
       ...,
       [array(['Good'], dtype='<U4')],
       [array(['Good'], dtype='<U4')],
       [array(['Bad'], dtype='<U3')]], dtype=object)), ('labels', array([[1],
       [2],
       [1],
       ...,
       [2],
       [2],
       [1]], dtype=uint8))])

In [15]:
Classes=labels["labels"]
Classes

array([[1],
       [2],
       [1],
       ...,
       [2],
       [2],
       [1]], dtype=uint8)

In [16]:
df1 = pd.DataFrame()

In [17]:
df_new = pd.concat([df1, pd.DataFrame(Classes)], axis=1)

In [18]:
df_new

0
0     1
1     2
2     1
3     2
4     2
...  ..
9672  2
9673  2
9674  2
9675  2
9676  1

[9677 rows x 1 columns]

In [22]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import RandomizedSearchCV

from sklearn import tree
clf = AdaBoostClassifier(learning_rate= 0.01, n_estimators=100)
A=np.mean(cross_val_score(clf,dataf_normalizedframe,df_new,cv=5,scoring="accuracy"))
r=np.mean(cross_val_score(clf,dataf_normalizedframe,df_new,cv=5,scoring="recall_weighted"))
p=np.mean(cross_val_score(clf,dataf_normalizedframe,df_new,cv=5,scoring="precision_weighted"))
print('A=',A*100)
print('r=',r*100)
print('p=',p*100)

C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  ret

A= 70.38338458581588
r= 70.38338458581588
p= 49.53821119172371


C:\Users\InfoMax\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
